### ISSUE TITLE
Crash with Json Things

### ISSUE THREAD

**Issue by paypur** [CCr4ft3r/lightspeed#1]
Game crashes on startup with Json Things installed. Removing Json Things allows the game to launch normally

[logs](https://mclo.gs/0Mk4vhQ)

**Comment by CCr4ft3r** [comment]
Thanks for reporting it - will be fixed asap.

**Comment by CCr4ft3r** [comment]
Really interesting reason for this crash - Json Things add constants to minecrafts code base at runtime 😅 Good to know what to look out for future optimizations.
Incompatibility is fixed in v0.3.1
