### ISSUE TITLE
Crash when starting dawncraft-1.6_hf integration package, lightspeed version 1.0.2

### ISSUE THREAD

**Issue by BlackRiceXY** [CCr4ft3r/lightspeed#11]

**Comment by CCr4ft3r** [comment]
Does not happen for me. Do use any other additional mods that are not included in the official modpack?
 Please provide the crash-report.txt

**Comment by CCr4ft3r** [comment]
This issue will be closed in one week if no further information is provided. If the problem still occur after closing this issue feel free to open a new one with all required information: MC version, Forge version, crash-report, latest.log/debug.log
