### ISSUE TITLE
[REQUEST] Config option to disable menu text line.

### ISSUE THREAD

**Issue by murao-kun** [CCr4ft3r/lightspeed#15]
I am making modpack with a custom text lines in menu. I wish to have option to disable the text line that mod adds.
![image](https://user-images.githubusercontent.com/110398598/231527855-ff738343-175b-4377-884f-455128640e4f.png)

**Comment by murao-kun** [comment]
This feature is helpful for pack devs, to see how modpack launch time is performing while you creating it. But I'd prefer that my users to not see it. Since it not really needed for them, if modpack optimized well.

**Comment by CCr4ft3r** [comment]
Please upload a screenshot that shows the named issue:  "So mod line is messing it a bit."
Ideally a screenshot covering the whole screen.

**Comment by murao-kun** [comment]
I am disabling every other line like minecraft version, forge version and MCP version. So I am lefting only pack name. But existing of that line is messing that idea a bit. That what I mean.

**Comment by CCr4ft3r** [comment]
Okay, I thought it was a real displaying issue.
To be honest and from my point of view it's not a good idea to let pack devs disable it. This text is like a lightweight, unobtrusive ad for me and for the mod. It's very hard for mods that didn't add anything visible to get publicity. Therefore I'm probably not going to add such an option. However moving it to another line I would be open to.

**Comment by murao-kun** [comment]
Can you have option to move it to the center and then disapper after some time passes, like 1 minute? And being placed under the MC logo itself. I guess that way it will have unique place to shine and solve the issue I have. As also being just a config option.

**Comment by CCr4ft3r** [comment]
Sounds like a good compromise to me 👍Even thirty seconds would be sufficient. 

I have thought about it a second time. Since you have accommodated me, I would like to do the same: 
What do you think of a solution that do not add the line at all when all other lines or all but except one were already removed? 
I think this would fulfill your requirement better. And would not enable others to remove it but only if they strive for a similar approach like you (an atmospheric one).

If you prefer this solution I only need to know how you removed the other lines. Did you removed the brandings from BrandingControl directly? Or do you use a specific mod for this? I only need to know to be sure that my solution can work at all.

**Comment by murao-kun** [comment]
I am using specific mod, that I will link down below. Thank you for considering such thing and supporting wishes to do aesphetic changes! I really like the mod and already recommending it to people if they asking for optimisation mods. But If I will end up posting my pack publically I will make sure to credit mod in special place, so every one would know how you can get that amazing results. :)
https://www.curseforge.com/minecraft/mc-mods/better-title-screen

**Comment by CCr4ft3r** [comment]
I truly appreciate your feedback. 
But please do me a favour: I appreciate it if you give me credit but please only like the other mods, no need to be in a special place. 
My previous message has to have sounded like I was trying to elicit sympathy. Now I have fully understand that pack devs just want to create a great experience for their users and mod devs should not get in the way of this.
Sorry that was kind of selfish of me to justify it with getting publicity. 

Thx for the mod. Give me two days and it will be published weekend at the latest.

**Comment by murao-kun** [comment]
To be true I really enjoing the mod and wish to make it more popular. The difference is so noticable, even more in big packs like my. If not special, I will find a good place to mention it for sure! Thank you for your kindness and understanding! Your mods are pretty helpful and interesting for creating amazing expiriences! Using all of your mods. :)

**Comment by murao-kun** [comment]
And also no need to rush! Implement it whatever you feel for that! I really appreciate your efforts and wishing you stay healthy and motivated for things you are doing!

**Comment by CCr4ft3r** [comment]
Thx, I wish you the same!

**Comment by CCr4ft3r** [comment]
Done :)
