### ISSUE TITLE
[1.19.2] Hang on startup with I Wanna Skate

### ISSUE THREAD

**Issue by abundzu** [CCr4ft3r/lightspeed#17]
Minecraft times out during startup with Lightspeed and I Wanna Skate (and citadel). Requires force close to kill client. Forge version 43.2.8.

[latest](https://mclo.gs/rAn7wyW)

**Comment by jahirxtrap** [comment]
Same here

**Comment by CCr4ft3r** [comment]
I fixed it. Thanks to @embeddedt for finding the cause. Will be included in 1.0.4
