### ISSUE TITLE
[1.16.5] Multiblocked textures are missing when lightspeed is loaded.

### ISSUE THREAD

**Issue by Gcat101** [CCr4ft3r/lightspeed#18]
Title.

![image](https://user-images.githubusercontent.com/79367505/235166072-f7ae9ce4-3543-4f68-afa5-4daff71755a6.png)
![image](https://user-images.githubusercontent.com/79367505/235166099-5d609a58-acdf-4a7b-ac86-2b924fd384cf.png)

To reproduce: Just add multiblocked and lightspeed to the same instance and launch it.

**Comment by CCr4ft3r** [comment]
Fixed. Will be included in version 1.0.4

**Comment by Gcat101** [comment]
epic
