### ISSUE TITLE
[1.18.2] Can't work with FullGrownCropMarker in my version of Better MC [FORGE] 1.18.2 v19 unless modlist count <= 95

### ISSUE THREAD

**Issue by qznfbnj** [CCr4ft3r/lightspeed#19]
**Describe the bug**
When I added [FullGrownCropMarker](https://github.com/tristankechlo/FullGrownCropMarker) into my version of [Better MC [FORGE] 1.18.2 v19](https://www.curseforge.com/minecraft/modpacks/better-mc-forge/files/4450626), it doesn't display marker unless modlist count <= 95
When the marker is not displayed properly with modlist count >= 96, F3+T will make it displayed normally, but it will take 3 minutes when used in my version of Better MC [FORGE] 1.18.2 v19.

Forge-1.18.2-40.2.1
crop-marker-forge-1.18.2-1.2.0
lightspeed-1.18.2-1.0.4

[debug.log(Can't display marker with modlist count 96)](https://gist.github.com/qznfbnj/fe226b76fbc0639867a35cb315879dee)
[debug.log(Display marker normally with modlist count 95)](https://gist.github.com/qznfbnj/66980e9487778d4095877dcad10854d0)

**To Reproduce**
1. Use FullGrownCropMarker with Better MC [FORGE] 1.18.2 v19, marker can't be displayed
2. Remove mods, but keep mod list count >= 96, marker still can't be displayed
3. Remove any mod, and marker can be displayed normally with mod list count 95
4. Remove lightspeed-1.0.4 and marker displayed normally with mod list count 341, so instead I reported to lightspeed's issue tracker. If this issue actually is FullGrownCropMarker's issue, I'll also open an issue on its issue tracker and link to this one.

**Screenshots**
Can't display marker with modlist count 96
![2023-05-14_16 17 08](https://github.com/tristankechlo/FullGrownCropMarker/assets/100760086/28b7a240-f75e-4ac7-bbfa-f4bd152d34e8)
![image](https://github.com/tristankechlo/FullGrownCropMarker/assets/100760086/586c8e3b-3a86-4317-bf89-a5d809cb1bb3)

Display marker normally with modlist count 95
![2023-05-14_16 30 52](https://github.com/tristankechlo/FullGrownCropMarker/assets/100760086/4a6e0755-a8f9-463a-a45a-0364a4d1303c)
![image](https://github.com/tristankechlo/FullGrownCropMarker/assets/100760086/ee32f91e-b0fa-40f2-af87-cae118e8d3b5)
↑In the log corresponding to the game instance that marker is not normally displayed, the code corresponding to the log segment that does not appear is [here](https://github.com/tristankechlo/FullGrownCropMarker/blob/797c8107d20767435b173891531d65a1b4316692/Common/src/main/java/com/tristankechlo/crop_marker/mixin/BlockModelMixin.java#L53).

Delete lightspeed-1.0.4 and marker displayed normally in my version of Better MC [FORGE] 1.18.2 v19
![image](https://github.com/tristankechlo/FullGrownCropMarker/assets/100760086/84e2c86b-9c25-480f-a724-6c3149511b50)

**Comment by CCr4ft3r** [comment]
Thank you for providing so much information - I fixed the issue and it will be included in the next feature update
