### ISSUE TITLE
Crash with Enhanced Farming (common setup phase)

### ISSUE THREAD

**Issue by Cixon** [CCr4ft3r/lightspeed#2]
**Mod in Question:**
https://www.curseforge.com/minecraft/mc-mods/enhanced-farming

**Crash-report:**
[crash-2023-02-18_21.06.23-fml.txt](https://github.com/CCr4ft3r/lightspeed/files/10775619/crash-2023-02-18_21.06.23-fml.txt)

**Log (line 475):**
[latest.log](https://github.com/CCr4ft3r/lightspeed/files/10775622/latest.log)

**Comment by Cixon** [comment]
Disabling enhanced farming via CFloader temporarily fix the issue. I believe this is the only mod in my personal mod-pack that has issues with Lightspeed. Great work thus far!

**Comment by CCr4ft3r** [comment]
Thank you for reporting it - I will fix it asap. I really appreciate your kind words

**Comment by CCr4ft3r** [comment]
Strangely, I cannot reproduce the error. I've just downloaded all of your mods except the following one and it just works fine:

herobrine: I cannot find a mod with this name

This mod is listed in your crash report:
Release.jar                                       |herobrine                     |herobrine                     |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE

The latest.log does contains the following line:
[21:02:56] [main/INFO]: Found mod file Release.jar of type MOD with provider {mods folder locator at C:\Users\***\curseforge\minecraft\Instances\Legacy\mods}

Is this mod not available on Curseforge?

Can you reproduce the upper error several times? Can you provide further information?

- Are you using resource packs? Which ones exactly?
- Are you using datapacks? Which ones exactly?
-  Can you export your modpack via Curseforge App and provide me the exported ZIP file?

Maybe the error only occur with specific versions of some mods.

**Comment by Cixon** [comment]
No resource packs but I am using a Herobrine mod and a data-pack for global mod.

Data-pack: https://www.curseforge.com/minecraft/customization/cut-clean
Mod-Link: https://www.curseforge.com/minecraft/mc-mods/origin-of-herobrine

**Comment by CCr4ft3r** [comment]
Thanks, but these also didn't triggered the error for me.
Can you export your modpack via the Curseforge App and provide me the exported ZIP file?
Maybe the error only occur with specific versions of some mods.

**Comment by Cixon** [comment]
oddly enough, i just got back home to test it and I got no crash this time... I dont know why this occurred. perhaps it was just a unlucky dedicated load? thank you for being patient with me!

**Comment by Cixon** [comment]
you may however follow my mod-pack here:
https://www.curseforge.com/minecraft/modpacks/legacy-forge

I will be using your lightspeed mod if that's okay? 😊

**Comment by CCr4ft3r** [comment]
I'm glad to hear that  - I have to thank you for providing all information and for your kind feedback🙂
I'll definitely take a look at your modpack to add further optimizations for it. 
Absolutely - I'm happy that you'll include Ligthspeed into your modpack.
