### ISSUE TITLE
[1.18.2] Compatibility Issues with ModernFix's Dynamic Resources feature

### ISSUE THREAD

**Issue by AzureAqua** [CCr4ft3r/lightspeed#20]
With both Lightspeed and ModernFix installed with mixin.perf.dynamic_resources=true in the ModernFix mixin config, the game will crash on second launch with certain mods installed, with broken namespaces such as Ars Nouveau and Create: Crystal Clear. Deleting the lightspeed cache folder will allow the game to launch again, but will crash again in the subsequent launch.
[crash-2023-05-21_00.35.45-client.txt](https://github.com/CCr4ft3r/lightspeed/files/11523369/crash-2023-05-21_00.35.45-client.txt)
[crash-2023-05-21_00.38.22-client.txt](https://github.com/CCr4ft3r/lightspeed/files/11523370/crash-2023-05-21_00.38.22-client.txt)

Additionally, using the same setup as above and having the Building Gadgets mod installed will cause the game to hang on launch.
[thread-dump.txt](https://github.com/CCr4ft3r/lightspeed/files/11523371/thread-dump.txt)

**Comment by AzureAqua** [comment]
Seems like this issue has been fixed on ModernFix's end.

**Comment by AzureAqua** [comment]
I think I might have accidently invalidated the lightspeed cache when I was testing, the final issue I mentioned with building gadgets and dynamic resources still seems to be a problem (the other issues have been fixed)

**Comment by CCr4ft3r** [comment]
Please update lightspeed to 1.0.5 and try again - the hang should be gone. 

Please describe the issue with Dynamic resources of Modernfix.

**Comment by AzureAqua** [comment]
Sorry, that was totally my bad. It seems like Prism's update checker didn't work for some reason and I never checked manually, so I was running a pretty old version. Thanks for fixing!

**Comment by CCr4ft3r** [comment]
No problem :)
