### ISSUE TITLE
[1.19.2] Performance issue

### ISSUE THREAD

**Issue by coco875** [CCr4ft3r/lightspeed#21]
When I have the mod my game is around 80-90 fps but without the mod I have more. So I think it should be interesting to not impact performance in game also

**Comment by CCr4ft3r** [comment]
Please provide the following information:
-forge version
-minimal reproducible setup: mods that need to be installed to trigger this issue

**Comment by coco875** [comment]
Forge: 43.2.11
I put the all pack because It's hard to find exactly the mod who make the slow
[pack.zip](https://github.com/CCr4ft3r/lightspeed/files/11574527/pack.zip)

**Comment by CCr4ft3r** [comment]
I cannot test every single mod in your modpack. In general all lightspeed caches will be invalidated after the launch. So normally lightspeed should not affect fps at runtime. 
So I still need a minimal reproducable setup.

**Comment by CCr4ft3r** [comment]
The mods of your pack seems inconspicuous to me. Typically Lightspeed does not execute any of it's code after the launch has finished. Furthermore I didn't profiled any CPU time of Lightspeed at runtime (after the launch).
Feel free to open a new issue if you can provide a minimal reproducable setup.
