### ISSUE TITLE
Texture error

### ISSUE THREAD

**Issue by ghost** [CCr4ft3r/lightspeed#22]
lightspeed-1.16.5-1.0.4
Seems to conflict with multiple mods

[latest.log](https://github.com/CCr4ft3r/lightspeed/files/11571802/latest.log)
![image](https://github.com/CCr4ft3r/lightspeed/assets/83486178/9a2d69f0-63a3-45ed-b2e4-fb2251513f81)

**Comment by CCr4ft3r** [comment]
Please list the mods

**Comment by ghost** [comment]
[modp-x.zip](https://github.com/CCr4ft3r/lightspeed/files/11571833/modp-x.zip)

**Comment by CCr4ft3r** [comment]
Only the mods that have the texture errors

**Comment by ghost** [comment]
> 只有有纹理错误的模组

It's hard to test. If other mods are tested with Lightspeed, there seems to be no texture issues.
But remove Lightspeed from modpack and the texture will be normal.

**Comment by ghost** [comment]
![image](https://github.com/CCr4ft3r/lightspeed/assets/83486178/1fe37446-1142-4fa6-a304-79363641ce15)

**Comment by ghost** [comment]
I don't know what to do, if you have a hard time fixing Lightspeed, I can use another mod instead of Lightspeed.

**Comment by ghost** [comment]
![image](https://github.com/CCr4ft3r/lightspeed/assets/83486178/1a702d74-e174-4255-900a-97c0a5e6cc55)
From other comments we know that the problem is absolutely real.

**Comment by CCr4ft3r** [comment]
Are you using a mod similar to Multiblocked?
I will look into the list later to check if there is any mod that affects similar places as lightspeed.

**Comment by CCr4ft3r** [comment]
Closed due lack of information - feel free to open a new issue when the affected mods are known
