### ISSUE TITLE
Incompatibility with Jicklus.

### ISSUE THREAD

**Issue by itzinstaplayzzz** [CCr4ft3r/lightspeed#23]
Hello, the game won't get out of the loading screen if Jicklus (https://www.curseforge.com/minecraft/texture-packs/jicklus) is installed alongside this mod. I've been removing mods in my pack, this is the only mod that conflicts with Jicklus.
I'm on version 1.16.5, Latest mod version.

**Comment by itzinstaplayzzz** [comment]
this will happen if the resource pack is enabled in game and then you try to launch.

**Comment by CCr4ft3r** [comment]
I cannot reproduce it with only installed Lightspeed and your resource pack.

**Comment by CCr4ft3r** [comment]
Closed due lack of information.
