### ISSUE TITLE
[1.16.5] Lightspeed Mod - Game crashed

### ISSUE THREAD

**Issue by Blu3M4n97** [CCr4ft3r/lightspeed#27]
Minecraft version: 1.16.5
Forge version: 1.16.5-forge-36.2.39
Mod version: lightspeed-1.16.5-1.0.5

The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered.
Exit Code: -1

Also, tried to load the game without the Lightspeed mod to confirm that it is wasn't this mod's fault. But without it Minecraft loaded fine. So, maybe a mod conflict with one of the other optimizations mods?

My other optimization mods installed:
Rubidium
Magnesium/Rubidium Extras
LazyDFU
Performant
FerriteCore

Attached a crash log.
[crash-2023-06-19_14.41.50-client.txt](https://github.com/CCr4ft3r/lightspeed/files/11787721/crash-2023-06-19_14.41.50-client.txt)

Also, attached a regular log. Hopefully this can help.
[2023-06-19-3.log.gz](https://github.com/CCr4ft3r/lightspeed/files/11787744/2023-06-19-3.log.gz)

**Comment by CCr4ft3r** [comment]
This crash is being caused by ModernFix. Please update it to the latest version.

**Comment by Blu3M4n97** [comment]
Okay, it is working now. Thank you!
