### ISSUE TITLE
Increased game loading time

### ISSUE THREAD

**Issue by MikiP98** [CCr4ft3r/lightspeed#31]
I have my own modpack, and with it the game starts in ~28s. After installing this mod, the game was launching for over 1 min. I wasn’t patient enough to let the game actually load so I don’t know how long it would take.
The (I think) only other mod aimed at decreasing loading time I have installed is “LazyDFU”.

**Comment by CCr4ft3r** [comment]
Please provide your modpack

**Comment by CCr4ft3r** [comment]
Which version of Lightspeed, Forge and Minecraft are you using?

**Comment by MikiP98** [comment]
Lightspeed version: 1.0.2
Forge version: 36.2.39
Minecraft version: 1.16.5

[modlist](https://github.com/CCr4ft3r/lightspeed/files/12147875/filenames.txt)
[modpackDownload](https://drive.google.com/file/d/1Gbimv42fbgMZ2_-UsNdhN3PQ6V08LVlv/view?pli=1)

**Comment by CCr4ft3r** [comment]
Please use version 1.0.5 - it should fix your issue

**Comment by CCr4ft3r** [comment]
There were multiple edge cases where the game didn't launched at all

**Comment by MikiP98** [comment]
Compiled and used 1.1.0. Game launched in whopping 19s! THX.
The newest version of the mod that's showing for me on modrinth is 1.0.2. I didn't find the version 1.0.5.

**Comment by CCr4ft3r** [comment]
Yeah unfortunately I'm only updating on CurseForge side only

**Comment by MikiP98** [comment]
I found this mod on the [UsefulMods list](https://github.com/TheUsefulLists/UsefulMods/blob/main/Performance/Performance116.md) and the primary link goes to modrinth.
I've managed to cut down the loading time to 16 seconds using this and 3 other mods. I've attached benchmarks
[Loading times.txt](https://github.com/CCr4ft3r/lightspeed/files/12148442/Loading.times.txt)

**Comment by CCr4ft3r** [comment]
Yeah, Modrinth is the preferenced platform for open source mods. However the majority of Minecraft users currently use CurseForge. I will probably also move to Modrinth completely if the majority has been too.
I've updated it on Modrinth to the latest versio now.
