### ISSUE TITLE
Lightspeed and Xaeros Minimap Crash

### ISSUE THREAD

**Issue by TheFlashmeister** [CCr4ft3r/lightspeed#33]
All versions of Lightspeed for 1.19.2 crashes with the Xaeros Minimap Mod.
Players are able to load the game and even join the world but for a split second after they do, the game will crash and bring up exit code -1.

**Comment by TheFlashmeister** [comment]
For more specification
[crash-2023-09-15_16.21.09-client.txt](https://github.com/CCr4ft3r/lightspeed/files/12623553/crash-2023-09-15_16.21.09-client.txt)
[latest.log](https://github.com/CCr4ft3r/lightspeed/files/12623554/latest.log)

Lightspeed 1.0.5 for 1.19.2
Xaeros Minimap 23.8.0 for 1.19.2

**Comment by CCr4ft3r** [comment]
The error doesn't seem to be related to Lightspeed.

I'm also using Lightspeed 1.0.5 for 1.19.2 and Xaeros Minimap 23**.5.**0 together without problems.
Does the crash still occur with 23.5.0?

If so, it's not being caused by Lightspeed. Then I would recommend a binary search.

**Comment by TheFlashmeister** [comment]
Did some further testing. Lightspeed 1.0.5 and Xaeros 23.8.0 both work together if they are on their own. 

They stop working together and producing a crash when you add Performant by SomeAddons into the mix.

**Comment by CCr4ft3r** [comment]
I would claim that the error still occurs when only using Performant and Xaeros minimap without Lightspeed.

If so, you would need to create an issue on their repo.

**Comment by CCr4ft3r** [comment]
Since the Performant mod is not available to the public I cannot test it with both mods

**Comment by CCr4ft3r** [comment]
Closed due the lack of information and mentioned reasons above.
