### ISSUE TITLE
has this being merged into the core of NeoForge?

### ISSUE THREAD

**Issue by ajaxnotmeta** [CCr4ft3r/lightspeed#37]
just as the title explains. has this mod became part of the core of NeoForge now that the thing wasnt related to the notorious dev of Forge loader and its anti changing approach to its old and slow code?

if so you can close this issue

**Comment by CCr4ft3r** [comment]
Im not aware about that but I think so (or otherwise in vanilla directly) ... at least some kind of similar. 
In Forge 1.20. the improvement of the launch time was negligible in comparison to 1.18.2 and 1.19.2
