### ISSUE TITLE
Crash on startup when using forge 40.1.73

### ISSUE THREAD

**Issue by supershorty1** [CCr4ft3r/lightspeed#5]
[crash-2023-03-12_13.00.36-client.txt](https://github.com/CCr4ft3r/lightspeed/files/10950006/crash-2023-03-12_13.00.36-client.txt)

**Comment by CCr4ft3r** [comment]
Thx for reporting it - I will look into it

**Comment by CCr4ft3r** [comment]
If you need an instant fix you can upgrade Forge to 40.1.86. However I will fix it anyway.

**Comment by supershorty1** [comment]
Thanks!

**Comment by CCr4ft3r** [comment]
Fixed in v1.0.1 - However I also noticed a higher memory usage with forge 40.1.73 than using 40.1.86. So I recommend to use the latest stable release of Forge.
