### ISSUE TITLE
[1.19.2] Resourcepack "Icons" not loading with OpenLoader properly

### ISSUE THREAD

**Issue by pewblaze** [CCr4ft3r/lightspeed#6]
Hi, im using Openloader to load my datapacks & resourcepacks -> the Icons arent loading properly with lightspeed installed. Without it it works fine. 

https://www.curseforge.com/minecraft/mc-mods/open-loader
https://www.curseforge.com/minecraft/texture-packs/icons

![grafik](https://user-images.githubusercontent.com/96242065/224816693-5879e3e1-80b8-4d61-93d6-9286e870c35d.png)

It should show the icons:
![grafik](https://user-images.githubusercontent.com/96242065/224817159-94d421d0-f4e9-4c69-baa8-01e3f322e236.png)

Im using 1.19.2 Forge 43.2.0
lightspeed-1.19.2-1.0.1
OpenLoader-Forge-1.19.2-15.0.1
Icons v.1.8pre2

Log if needed:
https://gist.github.com/pewblaze/fc96c1da13e25bf3351e8b7d3ea30437

**Comment by CCr4ft3r** [comment]
Oh that's really bad - I will fix it asap. Thx for reporting it.

**Comment by CCr4ft3r** [comment]
This seems like a strange incompatibilty between Lightspeed and another mod of your modpack - not related to OpenLoader or the Resource pack.

I tried a new modpack only including Lightspeed, Open Loader and the Icons Resource Packs and the Icons are being displayed correctly - also after restarting.

![openloader-icons](https://user-images.githubusercontent.com/118105353/225058195-7535f977-192e-4475-b726-c49d1050606f.jpg)

The log also does not contains any related errors.

**Comment by CCr4ft3r** [comment]
To fix this bug I probably need the information which mod is causing this issue.

**Comment by BookerCatch** [comment]
I was receiving a similar issue with a [resourcepack](https://www.curseforge.com/minecraft/texture-packs/visual-travelers-titles) that adds custom textures to the splash titles from [Traveler's Titles](https://www.curseforge.com/minecraft/mc-mods/travelers-titles). The conflicting mod appears to be Environmental. Disabling it from the pack restored the textured splash titles.

Here's what it should look like:
![image](https://user-images.githubusercontent.com/43504436/225143859-f07f3d04-4b35-4b09-b14d-d388f92e3a6f.png)

And here's what it looks like with Environmental toggled on:
![image](https://user-images.githubusercontent.com/43504436/225144246-b4efc923-4ed0-4764-84fd-afb71da4fd7b.png)

Please see log for any information that may help:
[latest.log](https://github.com/CCr4ft3r/lightspeed/files/10973904/latest.log)

**Comment by CCr4ft3r** [comment]
Thank you very much for this information - This helps me a lot. After some testing this issue always appears when both Lightspeed and Blueprint (a dependency of Environmental) are installed and activated.

I will look for a fix. Thx again - I appreciate your help.

**Comment by BookerCatch** [comment]
No problem! Your mod is wonderful and I'm eager to see it work in conjunction with other great mods.

I figured Blueprint might have been the culprit, but enabling Blueprint and a couple other of TeamAbnormal's mods like Clayworks, Buzzier Bees, and Abnormal's Delights doesn't cause an issue. I suppose it could be something *from* Blueprint that only occurs when engaging with a few of its problematic dependents. For instance, with the aforementioned mods enabled, adding Neapolitan on top of that brings the issue back. I hope this helps narrow down exactly what's happening by comparing the interactions between the problematic and non-problematic dependents.

**Comment by CCr4ft3r** [comment]
My bad - I messed up caching the resource loading  - issue is fixed in v1.0.2.
Thank you both for reporting it and providing further information.

**Comment by pewblaze** [comment]
Oh thanks for fixing! :D

**Comment by CCr4ft3r** [comment]
You're welcome 😃
