### ISSUE TITLE
[Suggestion] Port to 1.16.5

### ISSUE THREAD

**Issue by stantios** [CCr4ft3r/lightspeed#8]
Description: Basically the title. I see many popular modpacks that are getting frequently updated but are on 1.16.5 so it would be great if this mod could be ported to that version as it could help with modpacks drastically with loading times.

**Comment by CCr4ft3r** [comment]
There's already a 1.16.5 version of it - uploaded 3 days ago :) [https://www.curseforge.com/minecraft/mc-mods/lightspeedmod/files](https://www.curseforge.com/minecraft/mc-mods/lightspeedmod/files)

The launch time improvement is currently not as high as for 1.18.2 but still significantly and I'm trying to push it further.

**Comment by stantios** [comment]
Ah, I didn't know it was on CurseForge. I was looking on Modrinth for the 1.16.5 version

**Comment by CCr4ft3r** [comment]
oops you are right about that - I will upload it. Thx for informing me about it
